# Generated by Django 4.1.1 on 2023-07-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=3000, null=True)),
                ("writer", models.CharField(max_length=3000, null=True)),
                ("detail", models.TextField(null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("modified_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, null=True)),
                ("detail", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.article"
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.concept"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="concepts",
            field=models.ManyToManyField(
                through="app.ArticleConcept", to="app.concept"
            ),
        ),
    ]
