# Generated by Django 4.1.1 on 2023-07-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="detail", new_name="conclusion",
        ),
        migrations.AddField(
            model_name="article", name="content", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article", name="summary", field=models.TextField(null=True),
        ),
    ]
